# Generated by Django 4.2.7 on 2023-11-17 17:53

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beyondShop', '0009_alter_category_name_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255, unique=builtins.id),
        ),
    ]
